### PR TITLE
Enable builds for linux_aarch64 and linux_ppc64le

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
I did not noticed https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5645, this will be opened by the bot when ready.

**Comment by traversaro** [comment]
> I did not noticed [conda-forge/conda-forge-pinning-feedstock#5645](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5645), this will be opened by the bot when ready.

Actually for some reason the bot thinkgs that this is blocked by pyqt, let's see if that is true.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by jleibs** [comment]
> for some reason the bot thinks that this is blocked by pyqt,

Where are you seeing this?

**Comment by traversaro** [comment]
> > for some reason the bot thinks that this is blocked by pyqt,
> 
> Where are you seeing this?

In https://conda-forge.org/status/migration/aarch64andppc64leaddition .

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
I re-rendered manually as a workaround for https://github.com/conda-forge/conda-smithy/issues/1870 .

**Review by jleibs — APPROVED** [review]
This looks like what I would expect.

**Pull request merged**
